server:
  port: 9999
spring:
  data:
    mongodb:
      database: yuanyy
      password: yuanyy
      port: 10040
      host: 192.168.11.120
      username: yuanyy
      authentication-database: yuanyy
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true
