server:
  port: 9999
spring:
  data:
    mongodb:
      database: yuanyy
      password: yuanyy
      port: 10040
      host: 192.168.11.120
      username: yuanyy
      authentication-database: yuanyy
