server:
  port: 9999
spring:
  data:
    mongodb:
      database: annotator
      password: anno2019tator
      port: 10040
      host: 192.168.0.153
      username: annotator
      authentication-database: annotator
